
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car_database?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 215MB
server:
  port: 8383

