
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_customer_owner?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
#server:
#  port: 7676

jwt:
  secret: javainuse