
spring:
  application:
    name: employee-demo
  datasource:
    url: jdbc:mysql://localhost:3306/DBEmployee?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
      generate-ddl: true
      show-sql: true

