
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DBEmployee?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
  application:
    name: employee-demo
service:
  host: http://localhost:8081
  allocation:
    findAll: /services/allocation
    findByEmployeeId: /services/allocation/findByEmployeeId
